<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\NotificationService;

class TestNotifications extends Command
{
    protected $signature = 'notifications:test';
    protected $description = 'Send a test admin notification to all admin users (for debugging)';

    public function handle()
    {
        $count = NotificationService::notifyAdmins([
            'type' => 'system',
            'title' => 'Test Notification',
            'message' => 'This is a test notification generated by artisan command.',
            'data' => ['module' => 'admin.debug', 'note' => 'artisan test'],
            'related_id' => null,
            'related_type' => null,
        ]);

        $this->info("notifyAdmins returned: {$count}");

        return 0;
    }
}
